-- Voice Search — vehicles table + seed data (40 models from the prototype catalogue)
-- Run once:  mysql -u USER -p DATABASE < sql/install.sql
-- Already have a vehicles/models table? Skip CREATE, and instead add the FULLTEXT index
-- to your own table and map column names in api/search.php.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS vehicles (
  id           VARCHAR(80)  NOT NULL PRIMARY KEY,          -- slug, e.g. tata-curvv-ev
  name         VARCHAR(150) NOT NULL,
  brand        VARCHAR(80)  NOT NULL,
  type         ENUM('car','bike') NOT NULL,
  body         VARCHAR(40)  NULL,                          -- Hatchback, SUV, Scooter, Cruiser…
  fuel         VARCHAR(40)  NULL,                          -- Petrol, Diesel, CNG, Electric…
  seats        TINYINT      NULL,
  price_min    INT UNSIGNED NULL,                          -- ex-showroom, rupees
  price_max    INT UNSIGNED NULL,
  mileage      DECIMAL(6,2) NULL,                          -- kmpl, or km range for EVs
  rating       DECIMAL(2,1) NULL,
  transmission SET('manual','automatic') NULL,
  tags         TEXT NULL,                                  -- comma separated keywords
  use_cases    TEXT NULL,
  highlights   TEXT NULL,                                  -- pipe | separated, shown on cards
  features     TEXT NULL,
  url          VARCHAR(255) NULL,                          -- page URL; NULL = use url_pattern in config
  image_url    VARCHAR(255) NULL,
  status       TINYINT(1) NOT NULL DEFAULT 1,
  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_type_price (type, price_min, price_max),
  KEY idx_brand (brand),
  FULLTEXT KEY ft_search (name, brand, body, fuel, tags, use_cases, highlights, features)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO vehicles
 (id,name,brand,type,body,fuel,seats,price_min,price_max,mileage,rating,transmission,tags,use_cases,highlights,features)
VALUES
('maruti-swift','Maruti Suzuki Swift','Maruti Suzuki','car','Hatchback','Petrol',5,649000,964000,23.76,4.2,'manual,automatic','affordable, city, youngsters, first car, hatchback','city, daily commute, youngsters, first car','Best-in-class mileage | Lightest in segment | Easy to park','touchscreen, rearCamera, dualAirbags, abs'),
('maruti-baleno','Maruti Suzuki Baleno','Maruti Suzuki','car','Hatchback','Petrol',5,666000,969000,22.35,4.2,'manual,automatic','premium hatchback, feature packed, city','city, daily commute, premium hatchback','Head-up display | 360 camera | Large boot (318L)','touchscreen, rearCamera, 360camera, headUpDisplay, 6airbags'),
('maruti-brezza','Maruti Suzuki Brezza','Maruti Suzuki','car','Compact SUV','Petrol',5,834000,1414000,19.89,4.3,'manual,automatic','compact suv, popular, affordable suv','city, family, daily commute','Most affordable SUV with HUD | Strong resale value','touchscreen, rearCamera, sunroof, 6airbags, connectedCar, headUpDisplay'),
('maruti-ertiga','Maruti Suzuki Ertiga','Maruti Suzuki','car','MPV','Petrol',7,895000,1320000,20.3,4.3,'manual,automatic','7 seater, family, mpv, affordable 7 seater','family, 7 seater, daily commute, outstation','Most affordable 7-seater | Comfortable 3rd row | Smart Hybrid','touchscreen, rearCamera, 6airbags, thirdRowSeating'),
('maruti-grand-vitara','Maruti Suzuki Grand Vitara','Maruti Suzuki','car','SUV','Hybrid',5,1072000,2013000,27.97,4.4,'manual,automatic','suv, hybrid, mileage king, panoramic sunroof, eco','highway, family, eco-conscious, long drives','Best mileage SUV | Strong Hybrid option | Panoramic sunroof across variants','panoramicSunroof, touchscreen, 360camera, headUpDisplay, ventilatedSeats, 6airbags, connectedCar, strongHybrid'),
('hyundai-creta','Hyundai Creta','Hyundai','car','SUV','Petrol',5,1111000,2014000,17.4,4.4,'manual,automatic','suv, bestseller, 5 star ncap, adas, panoramic sunroof, premium','family, highway, city, premium','5-star NCAP | ADAS Level 2 | Panoramic sunroof | Bose sound system','panoramicSunroof, touchscreen, 360camera, ventilatedSeats, adas, 6airbags, connectedCar, bose, wirelessCharging'),
('hyundai-creta-ev','Hyundai Creta Electric','Hyundai','car','SUV','Electric',5,1799000,2399000,NULL,4.4,'automatic','electric, suv, long range, v2l, panoramic sunroof, 5 star ncap','electric, long range, premium, family, highway','V2L (power external devices) | 473 km range | 5-star NCAP | Digital side cameras','panoramicSunroof, touchscreen, 360camera, ventilatedSeats, adas, v2l, 6airbags, connectedCar, bose, wirelessCharging, digitalSideCamera'),
('hyundai-venue','Hyundai Venue','Hyundai','car','Compact SUV','Petrol',5,755000,1330000,18.15,4.2,'manual,automatic','compact suv, city, affordable suv, connected car','city, first suv, affordable suv','Connected car features | Compact and agile in city','touchscreen, rearCamera, sunroof, 6airbags, connectedCar'),
('hyundai-verna','Hyundai Verna','Hyundai','car','Sedan','Petrol',5,1099000,1765000,20.6,4.3,'manual,automatic','sedan, premium sedan, panoramic sunroof, adas, executive','highway, executive, premium sedan','Panoramic sunroof in sedan | ADAS Level 2 | Bose sound','panoramicSunroof, touchscreen, 360camera, ventilatedSeats, adas, 6airbags, bose, wirelessCharging'),
('hyundai-exter','Hyundai Exter','Hyundai','car','Micro SUV','Petrol',5,611000,1024000,19.4,4.1,'manual,automatic','micro suv, affordable, city, first car','city, first car, budget suv','Stylish micro-SUV | CNG variant available','touchscreen, rearCamera, 4airbags, sunroof'),
('tata-nexon','Tata Nexon','Tata','car','Compact SUV','Petrol',5,800000,1580000,17.01,4.2,'manual,automatic','compact suv, 5 star ncap, safe, adas, petrol diesel','family, city, daily commute, safe car','5-star NCAP | ADAS standard | Air purifier | Best safety in segment','touchscreen, rearCamera, sunroof, 6airbags, connectedCar, adas, airPurifier'),
('tata-nexon-ev','Tata Nexon EV','Tata','car','Compact SUV','Electric',5,1449000,2099000,NULL,4.3,'automatic','electric, suv, bestseller ev, 5 star ncap, fast charge','electric, city, daily commute, eco','Best-selling EV in India | 5-star NCAP | 60kW DC fast charge','touchscreen, rearCamera, sunroof, 6airbags, connectedCar, fastCharge, airPurifier'),
('tata-curvv-ev','Tata Curvv EV','Tata','car','Coupe SUV','Electric',5,1749000,2199000,NULL,4.4,'automatic','electric, coupe suv, long range, v2l, panoramic sunroof, jbl, adas, 5 star ncap','electric, premium, highway, long drives','502 km range | V2L feature | 5-star NCAP | Panoramic sunroof | 70 kW DC fast charge','panoramicSunroof, touchscreen, 360camera, ventilatedSeats, adas, v2l, 6airbags, jbl, connectedCar, fastCharge, wirelessCharging'),
('tata-punch','Tata Punch','Tata','car','Micro SUV','Petrol',5,600000,1029000,18.82,4.3,'manual,automatic','micro suv, 5 star ncap, safe, affordable, first car','city, first car, safe budget car','5-star NCAP in budget | Safest micro-SUV | CNG option available','touchscreen, rearCamera, 4airbags, connectedCar'),
('tata-punch-ev','Tata Punch EV','Tata','car','Micro SUV','Electric',5,999000,1429000,NULL,4.3,'automatic','electric, micro suv, affordable ev, 5 star ncap, first ev','electric, city, budget ev, first ev','Most affordable 5-star NCAP EV | 421 km range | Fast charge in 56 min','touchscreen, rearCamera, fastCharge, connectedCar, 4airbags'),
('tata-harrier','Tata Harrier','Tata','car','SUV','Diesel',5,1499000,2599000,16.8,4.3,'manual,automatic','suv, diesel, panoramic sunroof, 5 star ncap, jbl, adas, premium','highway, family, premium diesel','Panoramic sunroof | JBL audio | 5-star NCAP | ADAS Level 2','panoramicSunroof, touchscreen, 360camera, ventilatedSeats, adas, jbl, 6airbags, connectedCar'),
('tata-safari','Tata Safari','Tata','car','SUV','Diesel',7,1605000,2796000,16.3,4.3,'manual,automatic','7 seater, suv, diesel, panoramic sunroof, 5 star ncap, jbl, family','7 seater, family, highway, premium diesel','7-seater | Panoramic sunroof | 5-star NCAP | JBL audio','panoramicSunroof, touchscreen, 360camera, ventilatedSeats, adas, jbl, 6airbags, connectedCar, thirdRowSeating'),
('mahindra-xuv700','Mahindra XUV700','Mahindra','car','SUV','Petrol',7,1399000,2699000,15.63,4.5,'manual,automatic','7 seater, suv, 5 star ncap, adas, panoramic sunroof, bose, awd, flagship','7 seater, family, highway, premium, offroad','5-star NCAP | Level 2 ADAS | Panoramic sunroof | Bose audio | AWD available','panoramicSunroof, touchscreen, 360camera, ventilatedSeats, adas, driveSideAirbag, connectedCar, bose, wirelessCharging, awd'),
('mahindra-thar-roxx','Mahindra Thar Roxx','Mahindra','car','SUV','Petrol',5,1299000,2249000,15.2,4.4,'manual,automatic','suv, offroad, adventure, 4x4, 5 star ncap, rugged','offroad, adventure, highway, weekend drives','Best off-roader | 5-star NCAP | 4x4 with diff lock','sunroof, touchscreen, 360camera, 6airbags, connectedCar, 4x4, diff lock'),
('mahindra-scorpio-n','Mahindra Scorpio-N','Mahindra','car','SUV','Petrol',7,1399000,2469000,14,4.3,'manual,automatic','7 seater, suv, 5 star ncap, offroad, diesel','7 seater, family, offroad, highway','5-star NCAP | Powerful diesel option | 7-seater with 3rd row','sunroof, touchscreen, 6airbags, connectedCar, 4x4'),
('mahindra-xuv-3xo','Mahindra XUV 3XO','Mahindra','car','Compact SUV','Petrol',5,799000,1582000,17.96,4.3,'manual,automatic','compact suv, panoramic sunroof, 5 star ncap, affordable suv','city, family, first suv','Panoramic sunroof under ₹12L | 5-star NCAP | 360 camera','panoramicSunroof, touchscreen, 360camera, 6airbags, connectedCar'),
('honda-city','Honda City','Honda','car','Sedan','Petrol',5,1199000,1650000,18.4,4.3,'manual,automatic','sedan, honda, reliable, hybrid option, executive','highway, executive, premium sedan, family','32 kmpl Hybrid variant | Honda reliability | Premium sedan','touchscreen, rearCamera, 6airbags, laneWatch, connectedCar, sunroof'),
('honda-elevate','Honda Elevate','Honda','car','SUV','Petrol',5,1109000,1587000,15.26,4.2,'manual,automatic','suv, honda, reliable, family','family, city, highway','Smooth CVT | Honda reliability','sunroof, touchscreen, rearCamera, 6airbags, laneWatch'),
('kia-seltos','Kia Seltos','Kia','car','SUV','Petrol',5,1090000,2030000,16.5,4.3,'manual,automatic','suv, panoramic sunroof, bose, adas, ventilated seats, premium','premium, highway, family, feature-loaded','Bose premium audio | Panoramic sunroof | ADAS Level 2 | Ventilated seats','panoramicSunroof, touchscreen, 360camera, ventilatedSeats, adas, bose, 6airbags, connectedCar, wirelessCharging'),
('kia-carens','Kia Carens','Kia','car','MPV','Petrol',7,1050000,2082000,16.5,4.2,'manual,automatic','7 seater, mpv, panoramic sunroof, bose, family','7 seater, family, mpv, highway','Panoramic sunroof MPV | Bose audio | 3-row comfort','panoramicSunroof, touchscreen, 360camera, 6airbags, connectedCar, bose'),
('toyota-innova-hycross','Toyota Innova Hycross','Toyota','car','MPV','Hybrid',7,1899000,3045000,23.24,4.5,'automatic','7 seater, mpv, hybrid, luxury, panoramic sunroof, ottoman, premium','7 seater, highway, luxury mpv, family, chauffeur','Best-in-class 7-seater | 23 kmpl hybrid | Ottoman rear seats | Power sliding doors','panoramicSunroof, touchscreen, 360camera, ventilatedSeats, adas, 7airbags, ottoman seats, powerSlidingDoors, ottoman'),
('toyota-fortuner','Toyota Fortuner','Toyota','car','SUV','Diesel',7,3299000,5099000,10,4.4,'manual,automatic','suv, diesel, premium, 7 seater, 4x4, status car, high resale','premium, 7 seater, offroad, highway, status','Best resale value in class | 4x4 with low range | Iconic nameplate','sunroof, touchscreen, 360camera, ventilatedSeats, 7airbags, 4x4, connectedCar'),
('mg-hector','MG Hector','MG','car','SUV','Petrol',5,1399000,2199000,14.18,4.1,'manual,automatic','suv, panoramic sunroof, large screen, connected car','family, city, highway','Largest infotainment screen | Panoramic sunroof | Air purifier','panoramicSunroof, touchscreen, 360camera, 6airbags, connectedCar, airPurifier'),
('mg-windsor-ev','MG Windsor EV','MG','car','SUV','Electric',5,1399900,1599900,NULL,4.2,'automatic','electric, suv, panoramic sunroof, v2l, reclining seats, affordable ev','electric, city, comfortable ev','Reclining rear seats | V2L | Panoramic sunroof | Battery-as-a-service available','panoramicSunroof, touchscreen, recliningRearSeats, 6airbags, connectedCar, v2l'),
('volkswagen-taigun','Volkswagen Taigun','Volkswagen','car','Compact SUV','Petrol',5,1159000,1979000,19.04,4.3,'manual,automatic','compact suv, 5 star ncap, german, highway, premium, ventilated seats','highway, premium, spirited driving','5-star NCAP | German engineering | Best-in-class highway dynamics','sunroof, touchscreen, ventilatedSeats, 6airbags, connectedCar, wirelessCharging'),
('skoda-slavia','Skoda Slavia','Skoda','car','Sedan','Petrol',5,1089000,1879000,19.26,4.2,'manual,automatic','sedan, 5 star ncap, premium, ventilated seats, european','highway, premium sedan, spirited driving','5-star NCAP | Ventilated seats in sedan | Czech engineering','sunroof, touchscreen, ventilatedSeats, 6airbags, connectedCar, wirelessCharging'),
('renault-triber','Renault Triber','Renault','car','MPV','Petrol',7,615000,870000,19,4,'manual,automatic','7 seater, affordable, mpv, compact mpv, budget 7 seater','7 seater, affordable mpv, city, first car','Most affordable 7-seater in India | 4-star NCAP | Compact footprint','touchscreen, rearCamera, 4airbags'),
('re-classic-350','Royal Enfield Classic 350','Royal Enfield','bike','Cruiser','Petrol',2,193500,225000,35,4.3,'manual','cruiser, retro, touring, classic, royal enfield','touring, highway, weekend rides, retro enthusiast','Iconic retro styling | Tripper navigation | Comfortable for long rides','tripper, dualChannel abs, led lights'),
('honda-activa-6g','Honda Activa 6G','Honda','bike','Scooter','Petrol',2,74536,77536,60,4.3,'automatic','scooter, bestseller, commuter, family, practical','city, daily commute, family scooter','Best-selling scooter in India | 60 kmpl | H-Smart variant with Bluetooth','led lights, silent start, external fuel fill'),
('bajaj-pulsar-ns400','Bajaj Pulsar NS400Z','Bajaj','bike','Sports','Petrol',2,185000,197000,25,4.2,'manual','sports, performance, bajaj, highway, naked sports','performance, highway, daily commute','Largest Pulsar ever | TFT display | Slipper clutch','dualChannel abs, tft display, led lights, slipper clutch'),
('yamaha-r15-v4','Yamaha R15 V4','Yamaha','bike','Sports','Petrol',2,172000,182000,45,4.3,'manual','sports, track, yamaha, performance, vva','track, performance, sports enthusiast','Variable Valve Actuation | Traction control | MotoGP-inspired','traction control, quick shifter, led lights, tft display, dualChannel abs'),
('ola-s1-pro','Ola S1 Pro','Ola','bike','Scooter','Electric',2,147000,147000,NULL,4,'automatic','electric scooter, city, eco, smart','city, electric commute, eco','Touchscreen dashboard | Reverse mode | Fast charge','touchscreen, regen braking, hill assist, reverse mode'),
('hero-splendor-plus','Hero Splendor Plus','Hero','bike','Commuter','Petrol',2,77336,80136,80,4.2,'manual','commuter, mileage, economical, reliable, hero','daily commute, rural, economical','80 kmpl mileage | Most dependable commuter | Low maintenance','i3s idle stop, led daytime lights'),
('ktm-duke-390','KTM Duke 390','KTM','bike','Naked','Petrol',2,311000,311000,30,4.4,'manual','naked, performance, premium bike, ktm, electronics','performance, highway, spirited riding','Cornering ABS | 4 riding modes | Best-in-class electronics','cornering abs, traction control, quickshifter, tft display, lean sensor'),
('tvs-jupiter-125','TVS Jupiter 125','TVS','bike','Scooter','Petrol',2,83000,93000,62,4.2,'automatic','scooter, commuter, practical, family, tvs','city, daily commute, family scooter','62 kmpl | USB charging | Smooth ride quality','usb charging, led lights, bluetooth')
ON DUPLICATE KEY UPDATE name=VALUES(name), price_min=VALUES(price_min), price_max=VALUES(price_max);
